# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.3_1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.3_1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/skycloud/Desktop/vncsdk-1.5.1/samples/basicViewerMac

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/skycloud/Desktop/vncsdk-1.5.1/samples/basicViewerMac

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.3_1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.3_1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/skycloud/Desktop/vncsdk-1.5.1/samples/basicViewerMac/CMakeFiles /Users/skycloud/Desktop/vncsdk-1.5.1/samples/basicViewerMac/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/skycloud/Desktop/vncsdk-1.5.1/samples/basicViewerMac/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BasicViewerMac

# Build rule for target.
BasicViewerMac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicViewerMac
.PHONY : BasicViewerMac

# fast build rule for target.
BasicViewerMac/fast:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/build
.PHONY : BasicViewerMac/fast

AppDelegate.o: AppDelegate.mm.o

.PHONY : AppDelegate.o

# target to build an object file
AppDelegate.mm.o:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/AppDelegate.mm.o
.PHONY : AppDelegate.mm.o

AppDelegate.i: AppDelegate.mm.i

.PHONY : AppDelegate.i

# target to preprocess a source file
AppDelegate.mm.i:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/AppDelegate.mm.i
.PHONY : AppDelegate.mm.i

AppDelegate.s: AppDelegate.mm.s

.PHONY : AppDelegate.s

# target to generate assembly for a file
AppDelegate.mm.s:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/AppDelegate.mm.s
.PHONY : AppDelegate.mm.s

BasicViewerView.o: BasicViewerView.mm.o

.PHONY : BasicViewerView.o

# target to build an object file
BasicViewerView.mm.o:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/BasicViewerView.mm.o
.PHONY : BasicViewerView.mm.o

BasicViewerView.i: BasicViewerView.mm.i

.PHONY : BasicViewerView.i

# target to preprocess a source file
BasicViewerView.mm.i:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/BasicViewerView.mm.i
.PHONY : BasicViewerView.mm.i

BasicViewerView.s: BasicViewerView.mm.s

.PHONY : BasicViewerView.s

# target to generate assembly for a file
BasicViewerView.mm.s:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/BasicViewerView.mm.s
.PHONY : BasicViewerView.mm.s

main.o: main.mm.o

.PHONY : main.o

# target to build an object file
main.mm.o:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/main.mm.o
.PHONY : main.mm.o

main.i: main.mm.i

.PHONY : main.i

# target to preprocess a source file
main.mm.i:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/main.mm.i
.PHONY : main.mm.i

main.s: main.mm.s

.PHONY : main.s

# target to generate assembly for a file
main.mm.s:
	$(MAKE) -f CMakeFiles/BasicViewerMac.dir/build.make CMakeFiles/BasicViewerMac.dir/main.mm.s
.PHONY : main.mm.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... BasicViewerMac"
	@echo "... AppDelegate.o"
	@echo "... AppDelegate.i"
	@echo "... AppDelegate.s"
	@echo "... BasicViewerView.o"
	@echo "... BasicViewerView.i"
	@echo "... BasicViewerView.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

